server:
  port: 9003

spring:
  application:
    name: auth_service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=test_khoa_luan_v1;encrypt=true;trustServerCertificate=true
    username: sa
    password: 3568
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update # hoặc validate/create/drop tùy mục đích
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect