server:
  port: 9002

spring:
  application:
    name: router-server
  cloud:
    gateway:
      routes:
        - id: service-auth
          uri: lb://AUTH_SERVICE
          predicates:
            - Path=/auth_service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  
  instance:
    prefer-ip-address: true 