server:
  port: 9002

spring:
  application:
    name: router_server
  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://SERVICE1-SERVICE
          predicates:
            - Path=/service1/**