server:
  port: 9002

spring:
  application:
    name: router-server
  cloud:
    gateway:
      routes:
        - id: service-auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
        - id: service-product
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
        - id: service-user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - name: Authentication
        - id: service-card
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/card-service/**
          filters:
            - name: Authentication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  
  instance:
    prefer-ip-address: true 