server:
  port: 9002

spring:
  application:
    name: router_server
  cloud:
    gateway:
      routes:
        # - id: service1
        #   uri: lb://SERVICE1-SERVICE
        #   predicates:
        #     - Path=/service1/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  
  instance:
    prefer-ip-address: true 